name: Commit Notifier

on:
  schedule:
    - cron: '0 15 * * *'  # 매일 00:00(KST) 실행 (UTC 기준 15:00)
  workflow_dispatch:  # 수동 실행 추가

jobs:
  send-discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get today's commit count and author
        id: commit-info
        run: |
          # 이름 변환 함수
          convert_name() {
            case "$1" in
              "김지윤") echo "지윤" ;;
              "changhui-chan") echo "창희" ;;
              "수진") echo "수진" ;;
              "minim1nh") echo "수진" ;;
              "박지민") echo "지민" ;;
              *) echo "$1" ;;  # 매칭되지 않으면 원래 이름 반환
            esac
          }

          TODAY=$(date +'%Y-%m-%d')
          echo "오늘 날짜: $TODAY"

          # 각 커밋을 줄바꿈하여 출력하도록 수정
          COMMIT_INFO=$(git log --since="$TODAY 00:00:00" --until="$TODAY 23:59:59" --pretty=format:"%an%n")

          if [ -z "$COMMIT_INFO" ]; then
            echo "No commits today."
            exit 0
          fi

          # 작업자별 커밋 수를 셀 연관 배열 선언
          declare -A AUTHOR_COUNT

          while read -r AUTHOR; do
            # AUTHOR가 비어있는지 체크
            if [ -z "$AUTHOR" ]; then
              continue  # AUTHOR가 비어있으면 건너뛰기
            fi
            AUTHOR=$(convert_name "$AUTHOR")
            AUTHOR_COUNT["$AUTHOR"]=$((AUTHOR_COUNT["$AUTHOR"] + 1))
          done <<< "$COMMIT_INFO"

          MAPPED_INFO=""
          for AUTHOR in "${!AUTHOR_COUNT[@]}"; do
            MAPPED_INFO+="$AUTHOR: ${AUTHOR_COUNT[$AUTHOR] }"
          done

          MAPPED_INFO=${MAPPED_INFO%17}
          echo "MAPPED_INFO: $MAPPED_INFO"

          echo "::set-output name=commit-info::$MAPPED_INFO"

      - name: Send Discord notification
        run: |
          COMMIT_INFO="${{ steps.commit-info.outputs.commit-info }}"
          if [ -n "$COMMIT_INFO" ]; then
            MESSAGE="오늘의 커밋 인증! 🔥\n\n$COMMIT_INFO\n\n 잔디🌱를 심었습니다!"
            curl -X POST \
              -H "Content-Type: application/json" \
              -d "{\"content\": \"$MESSAGE\"}" \
              "https://discord.com/api/webhooks/1336742582201356361/b6hA4pZw82SSqJslIHxWnyFpfrY5MfPd4SGGTunvYITx8o5BvDzX6RDRw48KWgapzIRR"
          else
            echo "No commits to notify."
          fi