name: Commit Notifier

on:
  schedule:
    - cron: '0 15 * * *' # 매일 00:00(KST) 실행 (UTC 기준 15:00)
  workflow_dispatch: # 수동 실행 추가

jobs:
  send-discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get today's commit count and author
        id: commit-info
        run: |
          # 이름 변환 함수
          convert_name() {
            case "$1" in
              "김지윤") echo "지윤" ;;
              "changhui-chan") echo "창희" ;;
              "수진") echo "수진" ;;
              "minim1nh") echo "수진" ;;
              "박지민") echo "지민" ;;
              *) echo "$1" ;;  # 매칭되지 않으면 원래 이름 반환
            esac
          }

          # 기준 시간을 한국 시간으로 변환하여 출력
          TODAY=$(TZ="Asia/Seoul" date +'%Y-%m-%d')
          echo "오늘 날짜: $TODAY"

          # 디버깅용: 커밋 내역 전체 출력 (커밋 시간 포함)
          echo "디버깅용: 커밋 내역 출력"
          git log --since="$TODAY 00:00:00" --until="$TODAY 23:59:59" --pretty=format:"%an %ad" --date=iso

          # 각 커밋을 줄바꿈하여 출력하도록 수정
          COMMIT_INFO=$(git log --since="$TODAY 00:00:00" --until="$TODAY 23:59:59" --pretty=format:"%an%n")

          if [ -z "$COMMIT_INFO" ]; then
            echo "No commits today."
            exit 0
          fi

          declare -A AUTHOR_COUNT

          while read -r AUTHOR; do
            if [ -z "$AUTHOR" ]; then
              continue
            fi
            AUTHOR=$(convert_name "$AUTHOR")
            AUTHOR_COUNT["$AUTHOR"]=$((AUTHOR_COUNT["$AUTHOR"] + 1))
          done <<< "$COMMIT_INFO"

          # 작업자별 커밋 수 출력
          MAPPED_INFO=""
          for AUTHOR in "${!AUTHOR_COUNT[@]}"; do
            MAPPED_INFO+="$AUTHOR: ${AUTHOR_COUNT[$AUTHOR]}\n"
          done

          echo "commit-info=$MAPPED_INFO" >> $GITHUB_ENV

      - name: Send Discord notification
        run: |
          COMMIT_INFO="${{ env.commit-info }}"
          if [ -n "$COMMIT_INFO" ]; then
            MESSAGE="오늘의 커밋 인증! 🔥\n\n$COMMIT_INFO\n\n 잔디🌱를 심었습니다!"
            curl -X POST \
              -H "Content-Type: application/json" \
              -d "{\"content\": \"$MESSAGE\"}" \
              "https://discord.com/api/webhooks/1337071280008200233/Pcdye9ifgfCQ_Cvb5aFes1T4w_OPyMm2up61EW5s_-4pFKjK6fbmNtdcykbiY1bFp8xB"
          else
            echo "No commits to notify."
          fi
